"""add image in news

Revision ID: 06f8ce358b54
Revises: d6788d202efb
Create Date: 2022-03-16 15:37:59.273679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f8ce358b54'
down_revision = 'd6788d202efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('news_image_id_foreign', 'images', ['image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('news_image_id_foreign', type_='foreignkey')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
