"""Add old_id

Revision ID: 1952d93b8a57
Revises: 9ae59420fcbc
Create Date: 2022-04-28 12:11:21.629077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1952d93b8a57'
down_revision = '9ae59420fcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('computer_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('library_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('patents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('phonebook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('profkom_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('trademarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trademarks', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('profkom_news', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('phonebook', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('patents', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('library_news', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('computer_programs', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('catalog', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('old_id')

    # ### end Alembic commands ###
