"""initial

Revision ID: 40ecb4fe51b1
Revises: 
Create Date: 2022-02-25 10:50:25.768817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ecb4fe51b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_news',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('new_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['new_id'], ['news.id'], name='tag_new_new_id_foreign'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='tag_new_tag_id_foreign')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_news')
    op.drop_table('tags')
    op.drop_table('news')
    # ### end Alembic commands ###
