"""add preview image in news

Revision ID: 4ed8a40499db
Revises: 5e07aa18a806
Create Date: 2022-03-15 00:56:10.348186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed8a40499db'
down_revision = '5e07aa18a806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('news_preview_image_id_foreign', 'images', ['preview_image_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint('news_preview_image_id_foreign', type_='foreignkey')
        batch_op.drop_column('preview_image_id')

    # ### end Alembic commands ###
