"""add image and template tables

Revision ID: 5e07aa18a806
Revises: 40ecb4fe51b1
Create Date: 2022-03-15 00:48:33.300324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e07aa18a806'
down_revision = '40ecb4fe51b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates_news',
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('new_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['new_id'], ['news.id'], name='template_new_new_id_foreign'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name='template_new_template_id_foreign')
    )
    op.add_column('news', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('news', sa.Column('description', sa.String(), nullable=True))
    op.add_column('news', sa.Column('preview', sa.String(), nullable=True))
    op.add_column('news', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'created_at')
    op.drop_column('news', 'preview')
    op.drop_column('news', 'description')
    op.drop_column('news', 'slug')
    op.drop_table('templates_news')
    op.drop_table('templates')
    op.drop_table('properties')
    op.drop_table('images')
    # ### end Alembic commands ###
