"""set nullable preview image

Revision ID: d4942b729f07
Revises: 4ed8a40499db
Create Date: 2022-03-15 01:30:47.829120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4942b729f07'
down_revision = '4ed8a40499db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
