"""add groups

Revision ID: d6788d202efb
Revises: d4942b729f07
Create Date: 2022-03-16 15:16:27.629624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6788d202efb'
down_revision = 'd4942b729f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups_news',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('new_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='group_new_group_id_foreign'),
    sa.ForeignKeyConstraint(['new_id'], ['news.id'], name='group_new_new_id_foreign')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups_news')
    op.drop_table('groups')
    # ### end Alembic commands ###
